### ISSUE TITLE
原始数据怎么获取。

### ISSUE THREAD

**Issue by superqing001** [lemon234071/clean-dialog#6]
赞，非常好的工作。

想请教下一，知乎、微博、贴吧这些平台的原始数据一般是怎么获取的？

谢谢。

**Comment by lemon234071** [comment]
一般都是爬取的， 网上有一些已经爬取完的数据， 可以看下我们论文中的引用。https://github.com/thu-coai/CDial-GPT

**Comment by jesuswa** [comment]
果真是好数据
